var splashes = [
    "Surely I've frolicked too hard. I shall search for my punishment.",
    "Fact: a hat is a very good rabbit habitat. Thanks for that.",
    "I'm skipping work again, that's because I don't have a job.",
    "Have you ever carried a dozen bricks down a brick road, through a brick door and into a brick house?",
    "Actions speak louder than words, as long as you're mute.",
    "Just let it happen, let it happen.",
    "By the way, you shouldn't slouch in your chair. It's stunting your growth.",
    "WARNING !!! COMPLETELY UNVIABLE !",
    "No. Don't you touch my macaroni.",
    "Is that a bad guy or a lens flare?",
    "Nice one, you just caught yourself lacking.",
    "Always trying, trying my best to be good.",
    "The eight wonders of the world; Easter Island heads, the pyramids, y'know. Useless crap like that.",
    "The soup is cold, and the salad is hot. How is that even possible?",
    "Does <i>your</i> life have a pause control?",
    "Howdy! I wear a giant hat to compensate for...? Uhh... the sun?",
    "This isn't just Aron, this is Aron Pro.",
    "Who gives a fuck about an Oxford comma?",
    "Hippity hoppity, the child is no longer your property.",
    "You're winner!",
    "Your heart is wrong and must be removed.",
    "Play the new <i>George 2 (EARLY BUILD) copy</i> today for $3.99",
    "All our rides were... tested... for... safety... um.",
    "I don't care who the IRS sends, I am not paying taxes.",
    "STOP JUST STANDING THERE AND DO SOMETHING!!",
    "Florida is where logic goes on vacation.",
    "You have a body. Jennifers always have bodies.",
    "A good soldier leaves a dirtbag behind.",
    "She wouldn't buy me the game, so I broke the TV. She's unfair, you don't know, go away.",
    "Let's we go, amigo!",
    "A cheeseburger, for eating? Eat it.",
    "The jungle is on fire, go go run go go get to spaceship.",
    "That's a dead kid. Yup.",
    "At the end of the day, we've finally reached the peak.",
    "Hmm. We don't know the lyrics for this one.",
    "You'll have to guess the lyrics for this one.",
    "Looks like we don't have the lyrics for this song.",
    "You caught us, we're still working on getting lyrics for this one.",
    "Come on guys, stop mucking around. We only have five minutes until our show's on.",
    "I have risen, and the shaking has fallen.",
    "Judas, do not make it bad.",
    "Nahm ram xi mai cotton cotton cotton cotton cotton cotton cotton cotton store",
    "I knew I shouldn't have gotten those dodgy breast implants.",
    "Franklin grinned.",
    "The years of plodding on, in fear of the bubblegum dog.",
    "First of all, I just want you to know that I am a mother. Just as a mother is to her children, I am to them.",
    "<i>[SERVER] Illegal characters in chat message.</i>",
    "A profession I'd like to try for one day is... apple cider",
    "'Enigma of the Discount Bin', at top of the charts!",
    "You're going into orbit, you stupid mutt",
    "Remember kids, working together is better than alone.",
    "[Music] [Applause] [ __ ]",
    "Age seventy but fountain works, huh?",
    "It's so hard to get a plain cheese pizza these days.",
    "Alright, your speech organs seem fine.",
    "Spring your miracle, competite your level.",
    "I'm married to my job, but my job said we should see other people.",
    "Bush hid the facts.",
    "I wanna defy the logic of all sex(x) laws.",
    // violence
    "It's \"web site\" to me. I don't care what your \"website\" says.",
    "Look here bucko, \"web site\" at least stands out and doesn't interfere with that awful, woke \"website\" community.",
    "Mid CSS?! My good man, you update your site's CSS every 2 months! <i>And you're not even the one making it!</i> You're one to talk.",
    // violence ends
    "Communications with beef boss's Wii Remote have been interrupted.",
    "What do you mean you don't agree with me? Do you know who you're dealing with?!",
    "Hooray for me and my ability to remember stuff.",
    "I don't know if it's all made up...",
    "1919 was <b>20 years ago</b>.",
    "People of India are going <i>crazy</i> that President Obama was <i>constantly</i> chewing gum!",
    "...and then on top of that, he took it <i>out</i> of his mouth, then put it back- you can't do it, it's <i>disgusting</i>!",
    "Name an animal with three letters in its name, you said A L L I G A T O R",
    "The capital of Mexico is Mexico City. <i>seems plausible</i>",
    "From the earth I rise, and to the earth I one day will return.",
    "What's up, mothershuckers. My name is Colonel Cornelius Cornwall.",
    "Dude, Benson's gonna be so pissed.",
    "What is love? Fruit? No. Bread? No. Fruit and bread? Probably not.",
    "Look at you, so young and happy! Where did the years go?",
    "This product is vegan friendly.",
    "Jeeeeeez. Can she <i>be</i> more cringy?",
    "It's Deal-Tastic Me! And I bet this the most easiest decision you ever make!",
    "Don't marry the Wii. It's not that great, and it's really shallow.",
    "You see, using F5 gave me a whole new perspective and I was able to see a chest I couldn't have seen before.",
    "I have a rash in an uncomfortable place.",
    "As I pull down this file menu, you will notice the word 'hope' does not appear. You will also notice there is no command M for 'miracle'.",
    "If bowling is an analogy for life, then bowling makes sense. Because it makes no f***in' sense.",
    "\'In life is not if you nin or lose is if you me spice\', as the saying goes.",
    "So, we're technically canon, right?",
    "This contact lense represents you, and my eye represents my eye.",
    "Typically, veggies can't be carried from room to room. However, since it was stuck in his head, this didn't apply.",
    "Want to make more money? Here's how! Step 1: Have money. Step 2: Invest that money. 3. Profit.",
    "Minecraft 6",
    "We are human, after all. Much in common, after all.",
    "Buy it, use it, break it, fix it, trash it, change it, mail, upgrade it.",
    "No sauce is going to fix this atrocity.",
    "I don’t expect anything these days, so it is what it is.",
    "Why the f*** do you eat Toy Story action figures",
    "This marquee has given me too much power.",
    "Welcome to the George Series, you kinda joined at a low point.",
    "We don't have a bloomin' onion, we have a bloomin' PUMPKIN!",
    "Let's go on an adventure! Why? ...Because we're tighter than bark on a tree!",
    "Why does it take more than three squirrels to change a lightbulb? Because they're so darn stupid and ugli.",
    "Taking a bite of McDonald's Doom Burger tastes like heaven, the second bite can take you there.",
    "I know a good rye when I see one.",
    "FASTER MENNEREST!!!!!!!!!!!!!!!!!!!",
    "Tried to pull off his mask, but there was really his FACE!",
    "99% of gamblers quit before the big win!",
    "Someone stop this criminal, this is not forgivable!",
    "That evil individual, this is just unthinkable!",
    "Don’t you think this is all a little unfair? ...Yes.",
    "I am the yeast of thoughts and mind.",
    "New Objective: Wait in the line of slaves.",
    "Hey look, ramps! We can use these as ramps!",
    "Business. Serious business. This is absolutely all of your business.",
    "Oh look, SpongeBob and Patrick are on fire. This is going to be the best hunger games we have ever had.",
    "Kick some ice.",
    "What's it gonna take to shake the ill times?",
    "I'm thirsty- should be some orange juice in the fridge. ...I could go for a cup of coffee!",
    "I worked for George the Jumping Triangle, he's a fraud.",
    "SAVㅤㅤHㅤㅤINCㅤSS",
    "Holy crap- part of the Sound Shapes OST is on Spotify, we're so back",
    "This project has no meaningful contribution to society.",
    "Nothing puts a poop in a person's pants faster than talking about AI.",
    "Uh, hey- come look at this site. Aw, cool, can you download the Foo Fighters?",
    "*hysterical laughing* What a C-H-O-E-K.",
    "So before you speak, it's best to remember- each individual case will require a specific judgement call, depending on who you're talking to and the context of the conversation!",
    "A smile is like a hug that your face gives to someone else's eyes.",
    "Just remember the five D's of dodgeball: Dodge, Duck, Dip, Dive, and... Dodge.",
    "Water contains unhealthy amounts of water.",
    "This is my house dude. Don't jostle the heating ducts.",
    "Open your mouth wide... a universal sigh.",
    "I saw a guy do this in a toothpaste ad once.",
    "Where are my non-LG Productions-flavored blog posts?!",
    "For some reason, a lot of Minecraft Youtubers confuse 18 with 12.",
    "Where do these stairs go? ...They go up.",
    "This calls for an EMERGENCY FROG SITUATION.",
    "UI's are like jokes. If you have to explain them, they are not good.",
    "The Concord Situation of 2024 is crazy.",
    "Roll up, roll up for the Misery Tour!",
    "Unregistered HyperCam 2",
    "Ah, 'Snow White and the 7 Clever Boys' for the PS2, my favorite horror game.",
    "Majority of the rights reserved... I think.",
    "She didn’t have what it takes to survive in the cutthroat world of businesssssssss.",
    "'This world is mine to craft.' -Bryan, the Hero",
    "Bro made a guipplegorp-",
    "According to all known laws of physics, there is no way Java should be able to compile.",
    "No, I'm probably not okay :/",
    // ^ response to rylie eric quote
    "Keep it simple, don't overdo it.",
    "ＮＯ ＭＵＳＩＣ",
    "Thanks to you, I am a figure of ridicule within the market community.",
    "I'd like a new hat.",
    "We appreciate it very much, Tim Apple.",
    "I bought 99 boxes of ammo, and you're telling me not one person in this family had the ability to shoot Inspector Gadget with just one bullet before he stole 9 oxen?",
    "I'm the guy who listens to the same 5 songs and then switches them 2 months later",
    "This game makes no ham sense.",
    "You could stop at five or six stores, or just one. I can't stand it when she touches me.",
    "Did you just riff yourself?",
    "If you cannot push the button, I cannot help you.",
    "Beginner is too hard, we are going to intermediate.",
    "Avoid discussing how bad you think modern Minecraft or Mojang are. Everything that could possibly be said on this subject has been said by now.",
    "Hey, hey, hey! You're bad! You wanna try super beginner's course?",
    "The first night is never usually that Portuguese.",
    "HE JUMPED FOR THE BEEF???",
    "We've got the vision, now let's have some fun."
    // I NEED MORE SPLASHES SO NOW I WILL WATCH MORE YOUTUBE AND ABSOLUTELY NOTHING ELSE DURING MY FREETIME
];
document.getElementById("splashes").innerHTML = splashes[Math.floor(Math.random() * splashes.length)]
//why