var splashes = [
    "Surely I've frolicked too hard. I shall search for my punishment.", // the OG
    "Fact: a hat is a very good rabbit habitat. Thanks for that.",
    "I'm skipping work again, that's because I don't have a job.",
    "Have you ever carried a dozen bricks down a brick road, through a brick door and into a brick house?",
    "Actions speak louder than words, as long as you're mute.",
    "Just let it happen, let it happen.",
    "By the way, you shouldn't slouch in your chair. It's stunting your growth.",
    "WARNING !!! COMPLETELY UNVIABLE !",
    "No. Don't you touch my macaroni.",
    "Is that a bad guy or a lens flare?",
    "Nice one, you just caught yourself lacking.",
    "The eight wonders of the world; Easter Island heads, the pyramids, y'know. Useless crap like that.",
    "The soup is cold, and the salad is hot. How is that even possible?",
    "Does <i>your</i> life have a pause control?",
    "Howdy! I wear a giant hat to compensate for...? Uhh... the sun?",
    "This isn't just Aron, this is Aron Pro.",
    "Who gives a fuck about an Oxford comma?",
    "Hippity hoppity, the child is no longer your property.",
    "You're winner!",
    "Your heart is wrong and must be removed.",
    "Play the new <i>George 2 (EARLY BUILD) copy</i> today for $3.99",
    "All our rides were... tested... for... safety... um.",
    "I don't care who the IRS sends, I am not paying taxes.",
    "STOP JUST STANDING THERE AND DO SOMETHING!!",
    "Florida is where logic goes on vacation.",
    "You have a body. Jennifers always have bodies.",
    "A good soldier leaves a dirtbag behind.",
    "She wouldn't buy me the game, so I broke the TV. She's unfair, you don't know, go away.",
    "Let's we go, amigo!",
    "A cheeseburger, for eating? Eat it.",
    "The jungle is on fire, go go run go go get to spaceship.",
    "That's a dead kid. Yup.",
    "So... come here often?",
    "Hmm. We don't know the lyrics for this one.",
    "You'll have to guess the lyrics for this one.",
    "Looks like we don't have the lyrics for this song.",
    "You caught us, we're still working on getting lyrics for this one.",
    "Come on guys, stop mucking around. We only have five minutes until our show's on.",
    "I have risen, and the shaking has fallen.",
    "Judas, do not make it bad.",
    "Nahm ram xi mai cotton cotton cotton cotton cotton cotton cotton cotton store",
    "I knew I shouldn't have gotten those dodgy breast implants.",
    "Franklin grinned.",
    "The years of plodding on, in fear of the bubblegum dog.",
    "First of all, I just want you to know that I am a mother. Just as a mother is to her children, I am to them.",
    "<i>[SERVER] Illegal characters in chat message.</i>",
    "A profession I'd like to try for one day is... apple cider",
    "'Enigma of the Discount Bin', at top of the charts!",
    "You're going into orbit, you stupid mutt",
    "Remember kids, working together is better than alone.",
    "[Music] [Applause] [ __ ]",
    "Age seventy but fountain works, huh?",
    "It's so hard to get a plain cheese pizza these days.",
    "Alright, your speech organs seem fine.",
    "Spring your miracle, competite your level.",
    "I'm married to my job, but my job said we should see other people.",
    "Bush hid the facts.",
    "I wanna defy the logic of all sex(x) laws.",
    // violence
    'It\'s "web site" to me. I don\'t care what your "website" says.',
    'Look here bucko, "web site" at least stands out and doesn\'t interfere with that awful, woke "website" community.',
    "Mid CSS?! My good man, you update your site's CSS every 2 months! <i>And you're not even the one making it!</i> You're one to talk.",
    "Oh, please. Your main page has a spinning... thing that you *always* complain about not working properly! Don't get me started on trying to resize the pages, or even the half-baked sub-pages!",
    "What bricks? You mean the ones I threw at your window at 2am in the morning?",
    "I always kill the messenger. It's safer that way.",
    // violence ends
    "Communications with beef boss's Wii Remote have been interrupted.",
    "What do you mean you don't agree with me? Do you know who you're dealing with?!",
    "Hooray for me and my ability to remember stuff.",
    "I don't know if it's all made up.",
    "1919 was <b>20 years ago</b>.",
    "People of India are going <i>crazy</i> that President Obama was <i>constantly</i> chewing gum!",
    "...and then on top of that, he took it <i>out</i> of his mouth, then put it back- you can't do it, it's <i>disgusting</i>!",
    "Name an animal with three letters in its name, you said A L L I G A T O R",
    "The capital of Mexico is Mexico City. <i>seems plausible</i>",
    "From the earth I rise, and to the earth I one day will return.",
    "What's up, mothershuckers. My name is Colonel Cornelius Cornwall.",
    "Dude, Benson's gonna be so pissed.",
    "What is love? Fruit? No. Bread? No. Fruit and bread? Probably not.",
    "Look at you, so young and happy! Where did the years go?",
    "This product is vegan friendly.",
    "Jeeeeeez. Can she <i>be</i> more cringy?",
    "It's Deal-Tastic Me! And I bet this the most easiest decision you ever make!",
    "Don't marry the Wii. It's not that great, and it's really shallow.",
    "You see, using F5 gave me a whole new perspective and I was able to see a chest I couldn't have seen before.",
    "I have a rash in an uncomfortable place.",
    "As I pull down this file menu, you will notice the word 'hope' does not appear. You will also notice there is no command M for 'miracle'.",
    "If bowling is an analogy for life, then bowling makes sense. Because it makes no f***in' sense.",
    "'In life is not if you nin or lose is if you me spice', as the saying goes.",
    "So, we're technically canon, right?",
    "This contact lense represents you, and my eye represents my eye.",
    "Typically, veggies can't be carried from room to room. However, since it was stuck in his head, this didn't apply.",
    "Want to make more money? Here's how! Step 1: Have money. Step 2: Invest that money. 3. Profit.",
    "Minecraft 6",
    "We are human, after all. Much in common, after all.",
    "Buy it, use it, break it, fix it, trash it, change it, mail, upgrade it.",
    "No sauce is going to fix this atrocity.",
    "I don’t expect anything these days, so it is what it is.",
    "Why the f*** do you eat Toy Story action figures",
    "This marquee has given me too much power.",
    "Welcome to the George Series, you kinda joined at a low point.",
    "We don't have a bloomin' onion, we have a bloomin' PUMPKIN!",
    "Let's go on an adventure! Why? ...Because we're tighter than bark on a tree!",
    "Why does it take more than three squirrels to change a lightbulb? Because they're so darn stupid and ugli.",
    "Taking a bite of McDonald's Doom Burger tastes like heaven, the second bite can take you there.",
    "I know a good rye when I see one.",
    "FASTER MENNEREST!!!!!!!!!!!!!!!!!!!",
    "Tried to pull off his mask, but there was really his FACE!",
    "99% of gamblers quit before the big win!",
    "Someone stop this criminal, this is not forgivable!",
    "That evil individual, this is just unthinkable!",
    "Don’t you think this is all a little unfair?",
    "I am the yeast of thoughts and mind.",
    "New Objective: Wait in the line of slaves.",
    "Hey look, ramps! We can use these as ramps!",
    "Business. Serious business. This is absolutely all of your business.",
    "Oh look, SpongeBob and Patrick are on fire. This is going to be the best hunger games we have ever had.",
    "Kick some ice.",
    "What's it gonna take to shake the ill times?",
    "I'm thirsty- should be some orange juice in the fridge. I could go for a cup of coffee!",
    "I worked for George the Jumping Triangle, he's a fraud.",
    "SAV⠀⠀H⠀⠀INC⠀SS",
    "We're so back. Actually, we've been here the whole time.",
    "This project has no meaningful contribution to society.",
    "Nothing puts a poop in a person's pants faster than talking about AI.",
    "Uh, hey- come look at this site. Aw, cool, can you download the Foo Fighters?",
    "*hysterical laughing* What a C-H-O-E-K.",
    "So before you speak, it's best to remember- each individual case will require a specific judgement call, depending on who you're talking to and the context of the conversation!",
    "A smile is like a hug that your face gives to someone else's eyes.",
    "Just remember the five D's of dodgeball: Dodge, Duck, Dip, Dive, and... Dodge.",
    "Water contains unhealthy amounts of water.",
    "This is my house dude. Don't jostle the heating ducts.",
    "Open your mouth wide... a universal sigh.",
    "I saw a guy do this in a toothpaste ad once.",
    "Where are my non-LG Productions-flavored blog posts?!",
    "For some reason, a lot of Minecraft Youtubers confuse 18 with 12.",
    "Where do these stairs go? ...They go up.",
    "I would not put this in my top ten places I've ever been.",
    "This calls for an EMERGENCY FROG SITUATION.",
    "UI's are like jokes. If you have to explain them, they are not good.",
    "The [noun] Situation is [adjective].",
    "Roll up, roll up for the Misery Tour!",
    "Unregistered HyperCam 2",
    "Ah, 'Snow White and the 7 Clever Boys' for the PS2, my favorite horror game.",
    "Majority of the rights reserved... I think.",
    "She didn’t have what it takes to survive in the cutthroat world of businesssssssss.",
    "'This world is mine to craft.' -Bryan, the Hero",
    "Bro made a guipplegorp-",
    "According to all known laws of physics, there is no way Java should be able to compile.",
    "No, I'm probably not okay :/", // response to a rylie eric quote
    "Keep it simple, don't overdo it.",
    "ＮＯ ＭＵＳＩＣ",
    "Thanks to you, I am a figure of ridicule within the market community.",
    "I'd like a new hat.",
    "We appreciate it very much, Tim Apple.",
    "I bought 99 boxes of ammo, and you're telling me not one person in this family had the ability to shoot Inspector Gadget with just one bullet before he stole 9 oxen?",
    "I'm the guy who listens to the same 5 songs and then switches them 2 months later",
    "This game makes no ham sense.",
    "You could stop at five or six stores, or just one. I can't stand it when she touches me.",
    "Did you just riff yourself?",
    "If you cannot push the button, I cannot help you.",
    "Beginner is too hard, we are going to intermediate.",
    "Avoid discussing how bad you think modern Minecraft or Mojang are. Everything that could possibly be said on this subject has been said by now.",
    "Hey, hey, hey! You're bad! You wanna try super beginner's course?",
    "The first night is never usually that Portuguese.",
    "HE JUMPED FOR THE BEEF???",
    "It's over. He's done. He's finished. It got worse. He is done. It's done. He's ruined. Finally finished. The end. It's over.",
    "My boy. This peace is what all true warriors strive for.",
    "So what have you done? Some of your light has come to dirt!",
    "You know something has gone wrong when he switches to Chinese.",
    "Bentley is inviting people to his birthday party. If he invites 3 people, how many people are at the birthday?",
    "Just did a strange thing, now everything's pink.",
    "And the winner of the Bake-Off is... nine dismembered bodies.",
    "Why is it still raining? I did what I was supposed to. That's not fair.",
    "Once the sun starts to go down, it'll start to get dark.",
    "In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since.",
    "Are wii gonna have a problem? You best switch up that attitude!",
    "What are you, a pending transaction or what?",
    "The can of root beer soda started yapping about how muscular its thighs were, despite not knowing where or if it has any thighs.",
    "We've got drama and tension, and asteroids. Emotion, adventure, we've got it all!",
    "Join us. Thrive.",
    "I went to college for some reason. I don't know why I've done that.",
    "Joe, you gotta stop dying every few days. It's very bad.",
    "Speaking is not permitted during the debate.",
    "Don't let your dad pick out your clothes if he can't pick out his clothes.",
    "When life gives you lemons, make orange juice and let the world wonder how you did it.",
    "Man, wish my parents weren’t so divorced.",
    "Where are you Christmas? Why are you Christmas?",
    "Slackies; when you gotta go, but you don’t wanna leave.",
    "At this point, I feel like Jack Black is going to be cast for the voice in my head.",
    "I have never followed a rule. That is my rule. Do you follow? I don’t.",
    "This is now a safe city. I have punched a penguin into prison.",
    "Eat a dinner, Mattress Wayne.",
    "As a child, I yearned for the mines.",
    "There is no data.",
    "Why do I miss people who hurt me? That's because you're a dummy.",
    "Ron’s Ron shirt was just as bad as Ron himself.",
    "They looked at the door, screaming about how closed it was.",
    "h",
    "Max, what do you want for dinner?",
    "Free spring rolls and prawn crackers appreciated; toilet seat broken.",
    "Suggest to confine child and observe behavior.",
    "Contributed to alcohol abuse statistics; Love and laughter shared.",
    "Fluorine Uranium Carbon Potassium Bismuth Technetium Helium Sulfur Germanium Thulium Oxygen Neon Yttrium.",
    "Life is like a sardine... it’s small and kinda sucks.",
    "Not a flying toy.",
    "Duck forgot to drink water so now he is dead. Some sort of blob turns up.",
    "That's the way the cookie crumbles.",
    "Even if I wanted to, it's gone on further than it was supposed to.",
    "To put it simply, I myself create computerized games.",
    "Be sure to drink your Ovaltine.",
    "We don't need an unsupervised adult man karate chopping poor people in a halloween costume.",
    "The analysis is severely limited by my lack of understanding of what I am doing.",
    "Listening to LG Productions-brand music is not highly recommended.",
    "I can't stand Bethesda. You know they blow.",
    "Time is money, and you're gonna be penniless real soon.",
    "There's a Youtube glitch going around causing people to randomly unsubscribe.",
    "I'm a reasonable man, get off my case.",
    "Honey? More like phony, 'cause it's all fraudulent.",
    "Happy music makes me depressed.",
    "This is selling crap to kids who don't know better than to trust the people who are selling it to them. Do better.",
    "Please welcome to the stage, Thom Yorke and the Radioheads.",
    "I am in a contant state of Missouri.",
    "Do y'all ever get bored and download western Australia?",
    "If it exists, there’s a Tiger handheld version of it.",
    "34 hours! That's short for an RPG, but... that's long for somebody with a life.",
    "Before playing, read your operations manual for important information about your health and safety.",
    "You do not know how much you show, but the wind doth blow in the hills below?",
    "Commonly known not for making updates, but forcing others to update stuff about him.", // reference to nothing in particular
    "Why is no one having a good time? I specifically requested it.",
    "You can clean shrimp, good for you. You're not even a good person.",
    "You may not rest now, there are monsters nearby.", // took me waaaay too long to think of this
    "The power of one, the power of two, the power of mannnnyyyyy.",
    "I can't watch my clothes wash, because the washer needs to be closed for the clothes to wash.",
    "After a great meal, I like to lie on the floor and feel like garbage.",
    "ALPHYS updated status.",
    "A person's a person no matter how small, except to the point where they might actually be an ant.",
    "The creator lied to us.",
    "Renowned for taking 4 years to make a Scratch game.",
    "Every time I make music, I have to listen to an entire album to remind myself of what music actually sounds like.",
    "Are you telling me this clown's a level 4 naughty lister?",
    "Horton hears domestic violence in the next apartment and doesn't call 911.",
    "When there's a quota to meet, ethics go out the window.",
    "I was truly taken aback by the Minecraft of beta Minecraft... what have Minecraft been doing these days,,",
    "Human.. I remember you're <b>genocides</b>.",
    "Too old to order off the kids menu.",
    "Two days ago I was interrogating a sex shop employee about her work conditions.",
    "Lamp oil, rope, bombs? You want it? Too bad.",
    "Safety is an illusion, oblivion catches up with us all.",
    "A delaye, a dela. A delayed gamne, a delayepb. Bad Game Design.",
    "Legally questionable!",
    "A lonely child is what you're gonna be when I sell you.",
    "Oh, these dudes? They're the villagers!",
    "Coming in hot!",
    "That looks dubious to me. What do you think?",
    "I’ve checked every Gucci store on the planet looking for this baby.",
    "I f***ing hate it when the immutable power of the sun detonates in my room.",
    "Life is short. Have a Kitkat.",
    "Hello my good friend, I am the milk man here to serve fresh pasturized milk rich with vitamins and calcium.",
    "I'd rather have one Birdo than five children.",
    "Mario and Peach together, me and Gina together.",
    "Hot buttered popcorn, that's a deal!",
    "$29.99, none of that $60, multiplayer-only bullsh*t.",
    "I like you Jimmy, you're a spunky guy.",
    "This program is a cancer.",
    "The world is big. Class dismissed.",
    "Can the parrot sound like me?",
    "We're on Apple's magical black box, just in time for the holidays!",
    "Oh, you get crushes on cartoons? That's pretty cool.",
    "Mc. Mangos. Is. Suspended. Hahahahahaha. And that's keepin' it real.",
    "They're banging pots and pans, and chasing the game- sucking like lemons all over again.",
    "Hey bubby, I think you dropped an apple.",
    "Tomorrow is another day.",
    "So many things have already gone wrong, and it's because I can't read.",
    "Chadley, nobody cares about your stupid bathtub.",
    "I like to wear soft clothing ('cause it makes me feel like I'm rough, in comparison).",
    `You found the <span style="color:#6adf6c;">[Moss]</span>!`,
    "Think beyond antivirus, think Protegent.",
    "Now, although historically accurate, this site does not contain giant enemy crabs.",
    "I go in, fix one thing, and that causes 99 other things to fail.",
    "Hello, you magnificent bag of stardust and questionable decisions!",
    "Am I right lads, or am I right lads?",
    "I don't like something you're hosting and I'm going to sue you!",
    "I can't wait to drop off the Battle Bus and meet some of you on the battlefield in Fortnite.",
    "Thou shall not steal, thou shall not murder, thou shall not hijack another man's Yoshi.",
    "Acacia Wood came first, Minecraft was only a medium to realize it in.",
    "The image you are requesting does not exist or is no longer available.",
    "No problem here.",
    "Can snails help your garden? Um, not really.",
    "This girl is so sweet... let's give her free bullets!",
    "I'm sorry. I'm sorry about the pipes. I knew. I KNEW I shouldn't have done it.",
    "July 13th 2022. The silver bat incident.",
    "I don't know what happened, and that's what you should always tell the police.",
    "Like the West Coast, this land is beautiful, but I am homeless.",
    "Screw this, screw you, I have a right to sell drugs, I'm making a new nation!",
    "Pilot's license? What for?",
    "Technoblade never dies!",
    "You just saw a can of soda and the two neurons in your head fired for the first time in a week.",
    "ZERO calories, ZERO sugar, ZERO fat, kids love it, tastes like flavor.",
    "Black people, white people, men's team, women's team, coca-cola, pepsi-cola, rich people, poor people.",
    "You need to activate Windows before you can personalize your PC.",
    "Killing a baby donkey is a bad idea in practice.",
    "You might have chronic schizophrenia if you're drowning and think you'll respawn.",
    "If a player was born in Sweden, raised in America, and died in Mexico, what does that make him? Deceased.",
    "I'm the first second-generation Blizzard employee.",
    "My god, happy birthday, we got a gun.",
    "Oh, hello there! It's a bit cramped in here, but I'm making the most of it.",
    "The ash from the dead fish is stopping me from watching the living fish die.",
    "Experiencing interruptions? Find out why",
    "Remember, there's always money in the banana stand.",
    "He's a racist. Wait- wait, that's someone else!",
    "I am approximately 3 seconds away from wreaking havoc on my undergarments.",
    "It's not a masterpiece, it's a mistake.",
    "555 indicates a fake phone number, plus the rest of it is different every time the page is refreshed.",
    "Delaware ratified the U.S. Constitution in 1787.",
    "You cannot verify a level if it has a start pos.",
    "It looks like you may be using an ad blocker. Keep at it.",
    "Guys, you are about to have a fantastic adventure with the famous characters of the George Series!",
    "I see you are frustrated, would you like to be connected to a live agent?",
    "Big Z isn't real. I made him up",
    "He who befriends the oddest ball is the creepiest of them all.",
    "Crafting elegant digital experiences with modern technologies.",
    "Unlike the Donner party, cows can be bread with wheat for an achievement in Minecraft.",
    "I love being miserable and playing garbage. I want more.",
    "No Instagrammy, no Snappychat.",
    "You are not signed in and will be unable to save the game.",
    "I did not mean to hit publish, oops.",
    "Plans starting at $29.99 a month.",
    "Ping pong balls are great for ping, but not for pong.",
    "The world's not ready for Silly Steven!",
    "R is a programming language.",
    "How we you take i a little a place it La A Little I took a like... On did.",
    "You're a cinephile, I watch Family Guy.",
    "Hang on while Windows reports the problem to Microsoft..",
    "Water, fire, air, and dirt. F***in' magnets, how do they work?",
    "And so begins the revolution.",
    "I wake up, then I go to bed! I wake up, then I go to bed! I wake up, then I go to bed!",
    "I don't really know what to put here. This backing track is pretty dang cool.",
    "Talking to your friends can be hard if your coaming your hair at the same time",
    "The end is nigh, the end is null",
    "I'm on the world wide web. That flips my hat backwards!",
    "Okay, it's nighttime, and there's four dudes in my bed.",
    "We need to get the dodge out of hell. This cave is hell. This world is hell.",
    "What happens when an invincible bridge meets resurresctive antimatter?",
    "Your honour, shut up. You weren’t even there.",
    "The disk in drive A: is not the Font disk.",
    "My favorite M**vel Superhero's D**key Kong!",
    "versatile⠀⠀summary",
    "Alice went timidly up to the door, and stood there.",
    "We've got the vision, now let's have some fun."
    // "Overrated band... you will want to slit your wrists listening to [Radiohead's] music" and i took that personally
    // i find this quote funny, but it's too sensitive and kinda makes me upset thinking about it
];

function randomNum(max) {
    return Math.floor(Math.random() * max);
}

const totalSplashes = splashes.length;
const funChance = randomNum(totalSplashes) + 1;
document.getElementById("splashes").innerHTML = (funChance == 1) ? `${totalSplashes} splash texts and counting!` : splashes[randomNum(totalSplashes)];
